### ISSUE TITLE
Share link no longer works

### ISSUE THREAD

**Issue by fireattack** [jackyzy823/rajiko#10]
Version: 0.3.2

Share links such as http://radiko.jp/share/?sid=QRR&t=20230429260000 does not work anymore.

It redirects to https://radiko.jp/#!/out (`ラジコは、日本国内限定のサービスとなりますので、今アクセスしている場所からお聴きいただくことはできません。`).

Since I have Japan IP, these links *actually work without extension*. So basically, not only rajiko is unable to bypass the geo-restriction with share links, it prevents them from working even when having a Japan IP. 

I assume it's related to changed made in 0.3.2 a few days ago, either on rajiko's end or Radiko's end.

**Comment by jackyzy823** [comment]
Should be fixed in 0.3.3.

**Comment by fireattack** [comment]
Confirmed fixed, thanks!
