### ISSUE TITLE
0.3.3 Error message outside Japan

### ISSUE THREAD

**Issue by inoue64** [jackyzy823/rajiko#12]
Even in 0.3.3, when I open a new URL (from outside radiko or in a new tab), it seems that it is displayed as out of area (outside Japan).
(However, after opening radiko and closing the error message, if you click the link or paste the URL in the address bar and go to the playback page, it seems that you can play normally)
like
https://radiko.jp/
https://radiko.jp/#!/top
https://radiko.jp/#!/live/LFR
https://radiko.jp/#!/ts/LFR/20230510030000
https://radiko.jp/#!/timetable
https://radiko.jp/#!/timetable/LFR/live
https://radiko.jp/#!/recommend
https://radiko.jp/#!/search/timeshift?key=%E5%A4%A7%E5%89%8D%E3%82%8A%E3%82%87%E3%81%86%E3%81%99%E3%81%91
https://radiko.jp/share/?sid=LFR&t=20230510030000
(Only this one, the same display even if you enter it in the address bar of the URL with #! of radiko)
redirects to
https://radiko.jp/#!/out

**Comment by jackyzy823** [comment]
It looks like they update script today `https://radiko.jp/apps/js/area.js?_=20230511` . Need to find someway to workaround.

**Comment by jackyzy823** [comment]
Fixed in 0.3.4
