### ISSUE TITLE
about firefox android

### ISSUE THREAD

**Issue by Jimmy-Z** [jackyzy823/rajiko#16]
It looks like the supposed firefox android open extension GA hasn't arrived officially, but I just found out that if you just visit the addon page, you can install _some_ of them, like this one:

> https://addons.mozilla.org/en-US/firefox/addon/http-header-mangler/

But on rajiko's page, the "add to firefox" button is greyed out, I wonder why is that?

**Comment by jackyzy823** [comment]
It should be fixed in v0.3.6.1. Updated manifest key to allow AMO publishing addon for Android.
