### ISSUE TITLE
Handling special programs

### ISSUE THREAD

**Issue by mqg** [jackyzy823/rajiko#4]
Hello! Thank you for developing this great extension, and it has been really helpful! 

I ran into the rare instance where I want to listen / dl a radiko special program: https://radiko.jp/rg/special/autoreverse/

Listening works, but with download, I don't see the usual download timefree button. It remains on "confirm" view. 

Thanks for taking a look!

**Comment by jackyzy823** [comment]
Too lazy to handle special cases.

If you need it you could use the donwload link below.

https://send.vis.ee/download/59efa3b43ee220a8/#NxnbSWThYgOkERqF1VUjQw
password: autoreverse

Valid for 7 days or 20 downloads
